@startuml uml 03 - G3

Country o-- Province

@enduml

@startuml uml 03 - A3

note as sample
    示例代码
end note

@enduml

@startuml uml 03 - T1

class UseRecord
class AccountBook {
    - records: ArrayList<UseRecord>
    + queryByUser(user: User): UseRecord
    + queryByComputer(pc: Computer): UseRecord
    + addRecord(userId: String, pcId: String): void
}
class Admin

note top of Admin {
    假定只有唯一一个负责人（账户）
}

UseRecord -up-* AccountBook
Admin -- AccountBook

class User {
    - id: String
    + getId(): String
}

class Computer {
    - id: String
    + getId(): String
}

note top of User {
    假定只有当市民开始使用电脑后用户才被构造
}

User "0..*" --- "1..*" Computer

User "0..*" -left- "1" Admin

@enduml

@startuml uml 03 - T2

@enduml
